services:
  app:
    build:
      context: docker/.
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
      - ~/.ssh:/root/.ssh
    tty: true
    stdin_open: true
    depends_on:
      - db
    ports:
      - "8000:80"

  db:
    image: mariadb:latest
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: