openapi: 3.0.0
info:
  title: 'REST API'
  description: 'A simple REST API for demonstration purposes.'
  version: '1.0'
servers:
  -
    url: 'http://localhost:8000'
    description: 'Localhost server'
paths:
  /api/v1/task:
    get:
      summary: 'List all tasks'
      operationId: 2d5d6138b9740f742294c76ae513531b
      responses:
        '200':
          description: 'List of tasks'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
    post:
      summary: 'Create a new task'
      operationId: eb23ce239ca8bd00c85b6d91f22f485a
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: 'Task created'
        '400':
          description: 'Invalid input'
  '/api/v1/task/by-status/{status}':
    get:
      summary: 'List all tasks'
      operationId: 4a2cee6fe2ddefbd10bdc7f540f46b60
      parameters:
        -
          name: status
          in: path
          description: 'Status of the task'
          required: true
          schema:
            type: string
            enum:
              - todo
              - done
              - in_progress
      responses:
        '200':
          description: 'List of tasks filtered by status'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: 'Invalid input'
  '/api/v1/task/{id}':
    put:
      summary: 'Update a task'
      operationId: 5a3e9e725683015a3625b05f7156652a
      parameters:
        -
          name: id
          in: path
          description: 'ID of the task to update'
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: 'Task updated'
components:
  schemas:
    Task:
      required:
        - title
        - status
      properties:
        title:
          type: string
        status:
          type: string
        description:
          type: string
          nullable: true
      type: object
